/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.AnnouncementController;
import Controller.Logout;
import Controller.TimetableTableController;
import Model.Announcement;
import Model.AnnouncementArrayList;
import Model.AppContext;
import Model.Subject;
import Model.Teacher;
import Model.TimetableEntry;
import Model.User;
import java.awt.CardLayout;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Stack;
import javax.swing.BoxLayout;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kabil
 */
public class TeacherDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TeacherDashboard.class.getName());
    private Teacher teacher;
    AnnouncementArrayList announcements = AppContext.getAnnouncements();
    private Stack<Announcement> undoStack = new Stack<>();
    private ArrayList<TimetableEntry> filteredTimetable = new ArrayList<>();
    ArrayList<TimetableEntry> filteredEntries = new ArrayList<>();
    
    /**
     * Creates new form TeacherDashboard
     * @param teacher
     */
    public TeacherDashboard(User teacher) {
        this.teacher = (Teacher) teacher;
        initComponents();
        filterTeacherTimetable(this.teacher);
        TimetableTableController.updateFilteredTimetableTable(jTable2, filteredTimetable);
        displayUpcomingClass();
        AnnouncementController.updateAnnouncementTable(jTable3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Teacher Dashboard");

        jButton1.setText("Log out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 764, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton2.setText("Dashboard");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Announcement");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(476, Short.MAX_VALUE))
        );

        jPanel1.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Time Table");

        jTextField1.setText("Search");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton5.setText("🔎");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Day", "Start Time", "End Time", "Class", "Subject", "Teacher", "Room"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Upcoming class"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Message"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jButton6.setText("Send");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Send Announcements");

        jButton4.setText("Sort by day/time");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton8.setText("Filter");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Undo");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addGap(430, 430, 430)
                            .addComponent(jButton9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton6))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jButton8))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8)
                            .addComponent(jButton4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton9))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, "card2");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Announcement");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Message"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jButton7.setText("Send");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton10.setText("Undo");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Undo Stack"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable5);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton10))
                .addContainerGap(263, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Logout.logout(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "card2");
        filterTeacherTimetable(this.teacher);
        TimetableTableController.updateFilteredTimetableTable(jTable2, filteredTimetable);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "card3");
        AnnouncementController.updateAnnouncementTable(jTable4);
        updateUndoStackTable();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        // Show input dialog
        String message = JOptionPane.showInputDialog(
            this,
            "Enter announcement message:",
            "Send Announcement",
            JOptionPane.PLAIN_MESSAGE
        );

        // If user clicks Cancel
        if (message == null) {
            return;
        }

        // Validate empty input
        if (message.equals("")) {
            JOptionPane.showMessageDialog(
                this,
                "Announcement message cannot be empty.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // Create Announcement object
        Announcement announcement = new Announcement(message);

        // Add to queue
        announcements.addAnnouncement(announcement);
        undoStack.push(announcement);

        // Confirmation
        JOptionPane.showMessageDialog(
            this,
            "Announcement sent successfully.",
            "Success",
            JOptionPane.INFORMATION_MESSAGE
        );
        AnnouncementController.updateAnnouncementTable(jTable3);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        // Show input dialog
        String message = JOptionPane.showInputDialog(
            this,
            "Enter announcement message:",
            "Send Announcement",
            JOptionPane.PLAIN_MESSAGE
        );

        // If user clicks Cancel
        if (message == null) {
            return;
        }

        // Validate empty input
        if (message.equals("")) {
            JOptionPane.showMessageDialog(
                this,
                "Announcement message cannot be empty.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // Create Announcement object
        Announcement announcement = new Announcement(message);

        // Add to queue
        announcements.addAnnouncement(announcement);
        // Add to stack
        undoStack.push(announcement);

        // Confirmation
        JOptionPane.showMessageDialog(
            this,
            "Announcement sent successfully.",
            "Success",
            JOptionPane.INFORMATION_MESSAGE
        );
        AnnouncementController.updateAnnouncementTable(jTable4);
        updateUndoStackTable();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        sortTimetableByInsertionSort();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // Create dialog for filtering
        JPanel filterPanel = new JPanel();
        filterPanel.setLayout(new BoxLayout(filterPanel, BoxLayout.Y_AXIS));

        // Subject filter
        String[] subjects = AppContext.getSubjects().stream()
        .map(Subject::getSubjectName)
        .toArray(String[]::new);
        JComboBox<String> subjectComboBox = new JComboBox<>(subjects);
        subjectComboBox.insertItemAt("All Subjects", 0); // Add "All Subjects" option
        subjectComboBox.setSelectedIndex(0);

        // Day filter
        String[] days = {"All Days", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"};
        JComboBox<String> dayComboBox = new JComboBox<>(days);
        dayComboBox.setSelectedIndex(0);  // Default to "All Days"

        // Add filters to panel
        filterPanel.add(new JLabel("Select Subject:"));
        filterPanel.add(subjectComboBox);
        filterPanel.add(new JLabel("Select Day:"));
        filterPanel.add(dayComboBox);

        // Show dialog and handle input
        int option = JOptionPane.showConfirmDialog(this, filterPanel, "Filter Timetable", JOptionPane.OK_CANCEL_OPTION);

        if (option == JOptionPane.OK_OPTION) {
            // Fetch selected values
            String selectedSubject = (String) subjectComboBox.getSelectedItem();
            String selectedDay = (String) dayComboBox.getSelectedItem();

            // Filter timetable based on selected subject and day
            filterTimetable(selectedSubject, selectedDay);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String query = jTextField1.getText().trim();
        searchTimetable(query);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        undoLastAnnouncement();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        undoLastAnnouncement();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void undoLastAnnouncement() {
        if (undoStack.isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "No announcements to undo.",
                "Undo",
                JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }

        Announcement lastAnnouncement = undoStack.pop();
        announcements.getAllAnnouncements().remove(lastAnnouncement);

        AnnouncementController.updateAnnouncementTable(jTable3);
        AnnouncementController.updateAnnouncementTable(jTable4);
        updateUndoStackTable();


        JOptionPane.showMessageDialog(
            this,
            "Last announcement undone.",
            "Undo Successful",
            JOptionPane.INFORMATION_MESSAGE
        );
    }
    
    public void searchTimetable(String query) {
        // Ensure the query is not empty before searching
        if (query.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a search query.", "No Query", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Call the search method in TimetableTableController to get filtered timetable entries
        ArrayList<TimetableEntry> filteredEntries = TimetableTableController.searchTimetable(query, AppContext.getTimetable());

        // Update the timetable table with filtered results
        TimetableTableController.updateFilteredTimetableTable(jTable2, filteredEntries);
    }
    
    /**
     * Filters the timetable based on subject and day, and updates the table.
     * @param selectedSubject The selected subject for filtering
     * @param selectedDay The selected day for filtering
     */
    private void filterTimetable(String selectedSubject, String selectedDay) {
        ArrayList<TimetableEntry> timetableData = new ArrayList<>(AppContext.getTimetable().getEntries());
        
        filteredEntries.clear();
        // Filter based on subject and day
        for (TimetableEntry entry : timetableData) {
            boolean matchesSubject = selectedSubject.equals("All Subjects") || entry.getSubject().getSubjectName().equals(selectedSubject);
            boolean matchesDay = selectedDay.equals("All Days") || entry.getDay().equals(selectedDay);
            
            
            // If entry matches both filters, add it to the filtered list
            if (matchesSubject && matchesDay) {
                filteredEntries.add(entry);
            }
        }

        // Update the table with the filtered data
        TimetableTableController.updateFilteredTimetableTable(jTable2, filteredEntries);
    }
    
    public void sortTimetableByInsertionSort() {
        // Copy timetable entries to avoid modifying the original data
        ArrayList<TimetableEntry> entries = new ArrayList<>(filteredEntries);

        // Sort using Selection Sort
        TimetableTableController.sortTimetableByStartTimeInsertionSort(entries);

        // Update the table with the sorted entries
        TimetableTableController.updateFilteredTimetableTable(jTable2, entries);
    }
    
    public void filterTeacherTimetable(Teacher loggedInTeacher) {
        // Get the list of timetable entries
        ArrayList<TimetableEntry> timetableEntries = new ArrayList<>(AppContext.getTimetable().getEntries());

        // Filter the timetable by the logged-in teacher
        for (TimetableEntry entry : timetableEntries) {
            if (entry.getTeacher().getUserId().equals(loggedInTeacher.getUserId())) {
                filteredTimetable.add(entry);
            }
        }

        // Reuse the sorting logic from TimetableTableController
        TimetableTableController.sortTimetableByStartTimeInsertionSort(filteredTimetable);

        // Update the table with the filtered and sorted timetable
        TimetableTableController.updateFilteredTimetableTable(jTable2, filteredTimetable);
    }

    public void searchFilteredTimetable(String query) {
        // Use the search function from TimetableTableController to search in the filtered timetable
        ArrayList<TimetableEntry> searchResults = TimetableTableController.searchTimetable(query, filteredTimetable);

        // Update the table with search results
        TimetableTableController.updateFilteredTimetableTable(jTable2, searchResults);
    }

    public void sortFilteredTimetable() {
        // Reuse sorting method from TimetableTableController for filtered data
        TimetableTableController.sortTimetableByStartTimeInsertionSort(filteredTimetable);

        // Update the table with the sorted timetable
        TimetableTableController.updateFilteredTimetableTable(jTable2, filteredTimetable);
    }
    
    public void displayUpcomingClass() {
        String currentDay = java.time.LocalDate.now().getDayOfWeek().toString();
        currentDay = currentDay.substring(0,1) + currentDay.substring(1).toLowerCase();
        LocalTime currentTime = LocalDateTime.now().toLocalTime();

        ArrayList<TimetableEntry> timetableEntries = new ArrayList<>(filteredTimetable);

        // Sort the timetable entries by start time using selection sort
        selectionSortByStartTime(timetableEntries);

        int index = binarySearchForNextClass(timetableEntries, currentDay, currentTime);

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        if (index != -1) {
            TimetableEntry nextClass = timetableEntries.get(index);

            // Add each class detail in a separate row
            model.addRow(new Object[]{"Day: " + nextClass.getDay()});
            model.addRow(new Object[]{"Start Time: " + nextClass.getStartTime().toString()});
            model.addRow(new Object[]{"End Time: " + nextClass.getEndTime().toString()});
            model.addRow(new Object[]{"Class: " + nextClass.getClassName()});
            model.addRow(new Object[]{"Subject: " + nextClass.getSubject().getSubjectName()});
            model.addRow(new Object[]{"Teacher: " + nextClass.getTeacher().getName()});
            model.addRow(new Object[]{"Room: " + nextClass.getRoom()});
        } else {
            model.addRow(new Object[]{"No upcoming classes."});
        }
    }
    
    private void selectionSortByStartTime(ArrayList<TimetableEntry> timetableEntries) {
        for (int i = 0; i < timetableEntries.size() - 1; i++) {
            int minIndex = i;
            for (int j = i + 1; j < timetableEntries.size(); j++) {
                TimetableEntry entry1 = timetableEntries.get(minIndex);
                TimetableEntry entry2 = timetableEntries.get(j);
                if (entry2.getStartTime().isBefore(entry1.getStartTime())) {
                    minIndex = j;
                }
            }
            // Swap the elements
            TimetableEntry temp = timetableEntries.get(minIndex);
            timetableEntries.set(minIndex, timetableEntries.get(i));
            timetableEntries.set(i, temp);
        }
    }

    private int dayToIndex(String day) {
        if (day.equalsIgnoreCase("Monday")) return 1;
        if (day.equalsIgnoreCase("Tuesday")) return 2;
        if (day.equalsIgnoreCase("Wednesday")) return 3;
        if (day.equalsIgnoreCase("Thursday")) return 4;
        if (day.equalsIgnoreCase("Friday")) return 5;
        if (day.equalsIgnoreCase("Saturday")) return 6;
        return 7;
    }
    
    // Binary search method to find the next class based on current date and time
    private int binarySearchForNextClass(ArrayList<TimetableEntry> timetableEntries, String currentDay, LocalTime currentTime) {
        int low = 0;
        int high = timetableEntries.size() - 1;

        int currentDayIndex = dayToIndex(currentDay);

        while (low <= high) {
            int mid = low + (high - low) / 2;
            TimetableEntry entry = timetableEntries.get(mid);

            int entryDayIndex = dayToIndex(entry.getDay());

            boolean entryIsAfter =
                (entryDayIndex > currentDayIndex) ||
                (entryDayIndex == currentDayIndex && entry.getStartTime().isAfter(currentTime));

            if (entryIsAfter) {
                high = mid - 1;
            } else {
                low = mid + 1;
            }
        }

        if (low < timetableEntries.size()) {
            return low;
        }

        return -1;
    }
    
    private void updateUndoStackTable() {
        DefaultTableModel model = (DefaultTableModel) jTable5.getModel();
        model.setRowCount(0);

        // Top of stack should appear first in the table
        for (int i = undoStack.size() - 1; i >= 0; i--) {
            Announcement announcement = undoStack.get(i);
            model.addRow(new Object[]{announcement.getMessage()});
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new TeacherDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
